permissionlesstech/bitchat

bitchat/Services/BluetoothMeshService.swift, bitchat/Services/MessageRetentionService.swift
- Fixed threading issues causing crashes when users send messages
- Addressed all crash reports from TestFlight feedback
- Added `NSLock` to synchronize access to `recentlySentMessages` Set, preventing concurrent modification crashes
- Fixed thread-unsafe access to `activePeers` Set by using the existing `activePeersLock`
- Removed force unwrapping in `MessageRetentionService` and `BluetoothMeshService` that could cause crashes
- Added defensive input validation to prevent processing empty messages
Analyzed 6 crash reports from TestFlight:
- 5 crashes were due to thread-unsafe Set operations in `sendMessage`
- 1 crash was an iOS system issue (SVG rendering) outside our control
- All threading issues have been addressed with proper synchronization
=> Fix thread safety crashes in BluetoothMeshService

README.md, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/AppInfoView.swift, bitchat/Views/ContentView.swift
- Implement /block and /unblock commands for blocking peers
- Block by public key fingerprint for persistence across sessions
- Integration with favorites system (can't favorite blocked peers)
- Add commands to autocomplete and documentation
- /block <name> - blocks a peer from private messaging and ignores their messages in channels
- /block - lists currently blocked peers  
- /unblock <name> - unblocks a peer
- Blocked state persists using public key fingerprints
- Blocked peers automatically removed from favorites
=> Add block/unblock commands

bitchat/ViewModels/ChatViewModel.swift
This pull request addresses a potential race condition that could cause the app to crash or behave unexpectedly. I have added a dispatch to the main queue to ensure that all UI-related updates are performed on the main thread, which prevents crashes and unexpected UI behavior.
=> Fix: Ensure peer list updates on main thread

WHITEPAPER.md
Fixes markdown issue where ">60" appears as "Unsupported markdown: blockquote".
=> Fix Unsupported markdown: blockquote in README.md

bitchat/Views/ContentView.swift
- Send message button greyed out if textfield empty
- Shows confirmation alert before leaving channel (I accidentally tapped on leave whereas I wanted to tap on lock icon for password so it is good to show a confirmation)
- Currently, message textfield has auto correction enabled which has this weird bug (See video below)
https://github.com/user-attachments/assets/24d573b8-42a6-4d30-ab9d-17307eb91166
https://github.com/user-attachments/assets/b8681aaa-5a60-431b-92ac-daac7513032e
=> Fix for send message bug and other new features

bitchat/Views/LinkPreviewView.swift
Includes guard around `LPLinkMetadata` which only should work for iOS
Error Message when building for macOS:
```
~/bitchat/bitchat/Views/LinkPreviewView.swift:19:34 Cannot find type 'LPLinkMetadata' in scope
```
Change:
```
#if os(iOS)
@State private var metadata: LPLinkMetadata?
#endif
```
=> Fixing macOS build

bitchat/Utils/CompressionUtil.swift
This PR addresses a potential buffer overflow vulnerability in the compress function within CompressionUtil.swift. The original implementation allocated the destination buffer for compressed data with the size of the uncompressed data. In certain edge cases, compressed data can be larger than the original, leading to a buffer overflow. This fix allocates a larger, safer buffer for the compressed data using a common LZ4 worst-case heuristic (source_size + source_size / 255 + 16). This ensures that the buffer is always sufficiently large to prevent overflows, improving the stability and security of the compression utility.
=> Fix: Prevent potential buffer overflow in CompressionUtil.swift

BRING_THE_NOISE.md, bitchat.xcodeproj/project.pbxproj, bitchat/Protocols/BinaryProtocol.swift, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchatTests/BinaryProtocolVersionTests.swift, bitchatTests/ChannelVerificationTests.swift, bitchatTests/ProtocolVersionNegotiationTests.swift, bitchatTests/VersionNegotiationIntegrationTests.swift, bitchatTests/VersionNegotiationScenarioTests.swift
Implements protocol version negotiation to ensure compatibility between different BitChat client versions. This allows smooth protocol upgrades while maintaining full backward compatibility with existing clients.
- Added version negotiation message types:
- `0x20` versionHello - Initial version announcement 
- `0x21` versionAck - Version acknowledgment/agreement
- Added `ProtocolVersion` struct for version management
- Updated `BinaryProtocol` to check supported versions
- Version negotiation occurs before Noise handshake
- Clients exchange supported versions and agree on highest common version
- Legacy peers without version negotiation assume protocol v1
- Incompatible peers receive rejection message and disconnect gracefully
- Added comprehensive test suite with 40+ test cases
- Unit …
=> Add protocol version negotiation

bitchat/Noise/NoiseSession.swift, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/Services/NoiseEncryptionService.swift
- Implements Ed25519 signatures for identity announcements
- Fixes session persistence during peer ID rotation
- Fixes session destruction race condition causing handshake delays
- Added Ed25519 signing key pair to NoiseEncryptionService
- Keys are persisted securely in keychain alongside Noise static keys
- Updated NoiseIdentityAnnouncement to include signingPublicKey field
- Replaced HMAC signatures with proper Ed25519 signatures
- Fixed timestamp synchronization between signing and verification
- Added signature verification in PeerIdentityBinding
- Added session migration when peer IDs rotate via fingerprint tracking
- Sessions now follow peers across ID changes, preventing "No Noise session" errors
- Fixed race condition where peers would destroy established sessions when receiving …
=> Implement Ed25519 signatures and fix session management

bitchat.xcodeproj/project.pbxproj, bitchat/Noise/NoiseHandshakeCoordinator.swift, bitchat/Noise/NoiseProtocol.swift, bitchat/Noise/NoiseSession.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/Services/DeliveryTracker.swift, bitchat/Services/NoiseEncryptionService.swift, bitchat/Utils/SecureLogger.swift, bitchat/ViewModels/ChatViewModel.swift, bitchatTests/Integration/IntegrationTests.swift, bitchatTests/Noise/NoiseProtocolTests.swift
Fixes multiple issues with Noise protocol handshake stability, session synchronization, and peer reconnection handling.
- Peers stuck in "establishing encryption" state after restart
- Nonce desynchronization causing "Decryption failed at nonce N" errors
- Asymmetric peer visibility (one peer sees the other but not vice versa)
- Thread safety issues with concurrent encryption operations
- Sessions marked as stale immediately after establishment
- Missing read receipts during handshake transitions
- Add peer presence tracking with `lastHeardFromPeer` to detect reconnections
- Automatically send identity announcements when detecting peer reconnection after 30+ seconds
- Clear stale sessions when receiving handshake initiation from recently-seen peer (likely restart)
- Add peers to …
=> Fix Noise handshake stability and session synchronization

bitchat/Noise/NoiseHandshakeCoordinator.swift, bitchat/Noise/NoiseSession.swift, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift, bitchatTests/Integration/IntegrationTests.swift, bitchatTests/Noise/NoiseProtocolTests.swift
- Fixed handshake deadlock when one peer clears session but other rejects new handshake
- Improved connection state handling after disconnection/reconnection
- Added comprehensive logging for peer join/leave events
1. **Always accept handshake initiations** - Even if we have a valid session, accept new handshakes since the peer must have cleared their session for a good reason (decryption failure, restart, etc.)
2. **Fixed NACK handler** - Properly initiates handshake after clearing session on decryption failure
3. **Fixed identity announce relay** - Identity announce packets are now properly relayed through mesh network
4. **Improved handshake retry logic** - Added connection state checks and retry limits to prevent infinite loops
- `testHandshakeAlwaysAcceptedWithExistingSession` - …
=> Fix handshake deadlock and improve connection reliability

bitchat/Services/BluetoothMeshService.swift, bitchat/Views/ContentView.swift
- Fixed RSSI values showing as nil (hollow circles) in the UI when devices are connected
- Added mapping logic to handle announce packets that arrive via relay without peripheral reference
- Implemented periodic RSSI updates to keep signal strength values current
1. **Peripheral mapping fix**: When announce packets arrive via relay, map single unmapped peripherals to the announcing peer
2. **RSSI transfer**: Transfer RSSI values from temporary UUID to real peer ID when mapping is established
3. **Periodic updates**: Added timer to refresh RSSI values every 10 seconds for all connected peripherals
4. **Improved lookup**: Enhanced getPeerRSSI() to check multiple sources including known peers without peripherals
=> Fix RSSI nil display issue

bitchat/Identity/SecureIdentityStateManager.swift, bitchat/Protocols/BinaryProtocol.swift, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/AppInfoView.swift
- Fixed peer availability flapping by increasing timeout and fixing check logic
- Added BLE keepalive mechanism to maintain stable connections
- Resolved missing delivery ACKs issue in Noise encrypted messages
- Reduced network spam from identity announcements and keychain operations
- Implemented message retry system for failed deliveries
=> Improve BLE connection stability and message reliability

bitchat/Noise/NoiseProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift
This PR addresses the nonce desynchronization issue by sending the nonce over the wire. This should get rid of all desynchronization issues. I've fixed a bug related to parsing packages which leads to noise re-keying even if the session is ok (see comments below)
This update is compatible with the android PR https://github.com/permissionlesstech/bitchat-android/pull/181
The Noise protocol transport ciphers (`sendCipher` and `receiveCipher`) can become desynchronized when messages are lost, reordered, or when there are race conditions in concurrent message processing. When ciphers go out of sync, all subsequent encrypted messages fail to decrypt, requiring session renegotiation to restore communication.
This synchronization issue is particularly problematic in mesh networks where:
- …
=> NoiseProtocol update: send nonce in packet

bitchat.xcodeproj/project.pbxproj, bitchat/Info.plist, bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift
- Re-enabled cover traffic for enhanced privacy protection
- Fixed handshake to start immediately when opening PM conversation (not waiting for message send)
- Removed the handshake request system notification per user request
- Modified `triggerHandshake()` to always initiate handshake instead of using tie-breaker logic
- Set `coverTrafficEnabled = true` to restore privacy feature
- Commented out handshake request notification in UI
=> Fix lazy handshake behavior and re-enable cover traffic

project.yml
`just run` does not work right now because `swift-secp256k1` is not specified in `project.yml`. This PR fixes it
=> Adds swift-secp256k1 to project.yml

bitchat/Services/BluetoothMeshService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift
- Added alerts to notify users when Bluetooth is disabled or unauthorized
- Implemented real-time Bluetooth state monitoring
- Added Settings button for easy access to system Bluetooth settings
- **ChatViewModel**: Added Bluetooth state management and alert properties
- **BluetoothMeshService**: Reports Bluetooth state changes to the view model
- **ContentView**: Shows alert dialog with appropriate messages based on Bluetooth state
=> Add Bluetooth status alerts

AI_CONTEXT.md, README.md, bitchat/Services/BluetoothMeshService.swift
- Removes all cover traffic functionality from the codebase
- Simplifies the codebase by removing unused privacy feature
- Removed cover traffic variables and timer from BluetoothMeshService
- Removed cover traffic methods: `startCoverTraffic()`, `scheduleCoverTraffic()`, `sendDummyMessage()`, `generateDummyContent()`
- Removed cover traffic initialization in `startSession()`
- Removed cover traffic check in `handleReceivedPacket()` that filtered dummy messages
- Removed cover traffic timer invalidation in `reset()`
- Updated documentation (README.md and AI_CONTEXT.md) to remove cover traffic mentions
=> Remove cover traffic functionality

bitchat/Views/ContentView.swift
- Improves tap target size for better mobile usability
- Limits autocomplete suggestions for cleaner UI
- Increased tap target for back button in private message view from 12pt to 44x44pt while keeping visual size the same
- Limited @mentions autocomplete to show only top 4 matches instead of unlimited
=> Improve UI interactions

WHITEPAPER.md
Fixes an inaccurate description of Bloom filters and packet loss. Instead provides the actual reason to mitigate packet loss.
=> Clarify how packet loss is avoided with gossip protocol

bitchat/Nostr/NostrIdentity.swift, bitchat/Nostr/NostrProtocol.swift, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BluetoothMeshService.swift, bitchatTests/Integration/IntegrationTests.swift
This PR removes the protocol-level ACK/NACK system, relying instead on the gossip protocol's natural redundancy for message reliability.
- Remove message types 0x22 (protocolAck) and 0x23 (protocolNack)  
- Remove ProtocolAck and ProtocolNack data structures
- Remove ACK/NACK tracking collections (pendingAcks, acknowledgedPackets)
- Remove all ACK/NACK handling methods
- Simplify decryption failure recovery with immediate re-handshake
- Update integration tests for new behavior
- Fix P256K import issues (temporary until secp256k1 library added)
The gossip protocol provides sufficient reliability through:
- **Natural redundancy**: Multiple peers relay messages with adaptive probability
- **Path diversity**: Messages find alternative routes automatically  
- **Self-healing**: Network adapts …
=> Remove protocol ACK/NACK system in favor of gossip redundancy

bitchat/ViewModels/ChatViewModel.swift
The mention regex was defined with `a-zA-Z` which only allows "ASCII" characters. Replace it with `\p{L}` ("Letter" unicode category) to match special caracters like `ç` or `á`.
Note: this PR addresses nicknames/usernames. The same could be done with channels/hashtags names but maybe you want to keep those ascii?
See: https://regexr.com/8gf57
before:
after:
fixes #343
=> Allow unicode letter characters in nicknames

Justfile
In an Xcode project, `Index.noindex` is a special folder that Xcode uses to store its source code index database — basically all the metadata it needs for:
- Code completion (IntelliSense-like suggestions)
- Symbol navigation (jump to definition, find references)
- Refactoring tools
- Search indexing
=> Excludes Index.noindex in Justfile

bitchat/ViewModels/ChatViewModel.swift
Summary
- Unifies private message notifications across transports (mesh + Nostr geohash DMs).
- Sends notifications for truly unread and recent DMs even when the app is foregrounded; the notification delegate suppresses banners when the relevant chat is already open.
- Fixes geohash channel hydration to include the user’s own past kind 20000 events when loading/reloading a channel (skips only very recent self-echoes from relays to avoid duplicates).
Changes
- ChatViewModel
- DM notifications: remove iOS-only background checks for geohash DMs; notify on unread+recent when not viewing the chat.
- Geohash subscription handlers: skip only very recent self-echo (<15s); include older self events for hydration.
- Notification handling (unchanged but relevant)
- NotificationDelegate suppresses …
=> Unify DM notifications and fix geohash self-echo hydration

bitchat.xcodeproj/project.pbxproj, bitchat/Nostr/NostrProtocol.swift, bitchat/Nostr/XChaCha20Poly1305Compat.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift, bitchat/Views/MeshPeerList.swift, bitchatTests/NostrProtocolTests.swift
- Adopt NIP‑44 v2 for NIP‑17 DMs (gift wraps + seals) using XChaCha20‑Poly1305 with a "v2:" base64url format.
- Change sealed rumor kind to 14 per NIP‑17.
- Improve Schnorr signing (random aux RNG per BIP‑340).
- Fix unwrap parity (x‑only pubkeys): try both even/odd Y for ECDH.
- Ensure delivered/read acks are sent over Nostr even without Noise mapping (geohash‑style fallback).
- Fix DM autoscroll (correct item IDs so scrollTo targets exist).
- Mesh Peer List: radio icon for mesh‑connected; purple globe for mutual favorite/Nostr.
- Add unit tests for NIP‑44 v2 ACK round‑trip.
- Removed legacy AES‑GCM ad‑hoc ciphertext. Only NIP‑44 v2 is emitted/accepted now. Previously sent AES‑GCM DMs will not decrypt.
- Nostr encryption:
- Switch AES‑GCM → XChaCha20‑Poly1305, encode as `v2:` + …
=> NIP‑17/44: XChaCha20 v2 gift wraps, DM kind=14, receipts + UI fixes

bitchat.xcodeproj/project.pbxproj, bitchat/BitchatApp.swift, bitchat/Info.plist, bitchat/Protocols/BitchatProtocol.swift, bitchat/Services/BLEService.swift, bitchat/Services/CommandProcessor.swift, bitchat/Services/Transport.swift, bitchat/Services/VerificationService.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift, bitchat/Views/FingerprintView.swift, bitchat/Views/MeshPeerList.swift, bitchat/Views/VerificationViews.swift
This PR implements a secure, QR-based verification flow that binds a mesh peer’s cryptographic identity to the human you meet in person. It uses a signed QR plus a live challenge/response exchange over the existing Noise channel. The work also adds immediate persistence for verified status, shows verified badges for offline favorites, polishes the VERIFY sheet, and speeds up first-open performance.
- Strongly ties the person you meet to the device’s Noise identity (no nickname spoofing).
- Live possession proof prevents copying someone else’s QR or replaying old codes.
- Improves UX (no manual fingerprint compare) while maintaining privacy.
- Optional Nostr linkage (via npub) for future cross-transport features.
1. Generate QR (on Device A):
- Fields: `v`, `noiseKeyHex`, `signKeyHex` …
=> QR verification: live challenge/response over Noise; persistence, offline badges, and UX/perf polish

README.md
BitChat's hybrid architecture (Bluetooth mesh + Nostr internet protocol) wasn't documented, causing confusion about how location channels work across large geographic areas despite Bluetooth's limited range, and when internet is required vs. optional.
- Updated project description to clarify dual transport architecture
- Added Technical Architecture section explaining:
- Bluetooth mesh (offline, local, multi-hop)
- Nostr protocol (internet-based, global relays)
- Channel types and routing logic
- Clarified geohash precision levels for location channels
=> Update README to explain hybrid messaging architecture, nostr integration, and channels

bitchat/BitchatApp.swift, bitchat/Services/LocationChannelManager.swift, bitchat/Services/NotificationService.swift, bitchat/Services/TransportConfig.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/LocationChannelsSheet.swift
- Use minimal-distance hue palette for mesh and geohash lists; align chat sender colors with list palette.
- Add foreground geo notifications for different channels; deep-link to bitchat://geohash/<gh>; per-geohash 60s cooldown; respect self/blocks.
- Global geohash sampling runs outside the sheet; delegate handles deeplinks and suppresses when already in-channel.
- Switch location channel sheet to continuous CoreLocation with 21m distance filter; add config knob.
- Only link geohash hashtags when standalone (no @name#abcd or word#abcd).
- Include mesh-reachable peers in mesh counts and in "bitchatters nearby" notification.
- Add TransportConfig knobs for palette and geo notifications.
=> UI: diversify peer colors; smarter geo notifications; 21m live location

bitchat/Services/LocationChannelManager.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift
This PR improves geohash user experience.\n\nChanges:\n- Remove "new chats!" background nudge; instead, send notifications only when a regional geohash goes from 0 participants to activity, with content preview and cooldown.\n- Correct teleport behavior: if the selected geohash is in the current regional channel list, do not mark teleported; clear persisted teleport flags when in-region; avoid marking self teleported from historical "teleport" tags; deep links don’t mark teleported for regional geohashes or during cold start.\n- Sort per-geohash timelines chronologically on re-entry and trim whitespace-only content to prevent blank lines.\n- Trim inbound public content and ignore whitespace-only sends.\n\nTouches:\n- ChatViewModel.swift\n- LocationChannelManager.swift\n- …
=> Fix geohash UX: rising-edge notify, correct teleport, sort timeline

bitchat.xcodeproj/project.pbxproj, bitchat/Protocols/Geohash.swift, bitchat/Services/GeohashBookmarksStore.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift, bitchat/Views/LocationChannelsSheet.swift, bitchatTests/GeohashBookmarksStoreTests.swift
- Add bookmarking for geohash channels with persistence and UI.
- Subscribe to activity for nearby + bookmarked geohashes.
- Send geohash notifications only on rising-edge (0 → alive) with freshness/cooldown guards.
- Pre-populate timelines so notification-triggering messages appear when opened.
- Resolve and persist friendly names for bookmarks.
- `GeohashBookmarksStore` (new):
- `@Published bookmarks: [String]`, `bookmarkNames: [String: String]` (UserDefaults)
- APIs: `isBookmarked(_:)`, `toggle(_:)`, `add(_:)`, `remove(_:)`, `resolveNameIfNeeded(for:)`
- Normalizes geohashes (lowercase base32; strips `#`), MRU on add; dedupes
- Reverse geocoding of friendly names at bookmark time
- For very coarse geohashes (length ≤ 2), sample multiple corners and compose a combined label (e.g., …
=> Geohash Bookmarks + Rising‑Edge Notifications + Friendly Names

bitchat.xcodeproj/project.pbxproj, bitchat/Nostr/NostrProtocol.swift, bitchat/Nostr/NostrRelayManager.swift, bitchat/Protocols/LocationChannel.swift, bitchat/Services/LocationChannelManager.swift, bitchat/Services/LocationNotesCounter.swift, bitchat/Services/LocationNotesManager.swift, bitchat/Services/TransportConfig.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift, bitchat/Views/LocationChannelsSheet.swift, bitchat/Views/LocationNotesSheet.swift, bitchat/Views/LocationNotesView.swift
This draft PR adds location notes (Nostr kind 1) scoped to the current building (geohash precision 8), with a focused UI flow and careful perf/UX behavior:
- Publish/view kind‑1 notes tagged with `#g=<geohash>` and optional `#n=<nickname>` (no teleport tag)
- Mesh toolbar notes entry (icon blue when notes exist, grey otherwise)
- A dedicated notes sheet that follows your current building as you walk (live updates with 10 m distance filter)
- Haptic on building change while the sheet is open (iOS)
- Count moved into sheet header (“1 note @ #ghash” / “N notes @ #ghash”)
- Reverse‑geocoded building name (fallback: block) displayed under the title
- EOSE handling for subscriptions (initial load completion) with safe 2s fallback
- Uses GeoRelays for send/subscribe (closest relays by geohash)
- …
=> Location Notes (kind 1) at Building Precision + Live Updates

bitchat/BitchatApp.swift, bitchat/Nostr/NostrRelayManager.swift, bitchat/Services/NetworkActivationService.swift, bitchat/Services/Tor/TorManager.swift, bitchat/Services/Tor/TorNotifications.swift, bitchat/ViewModels/ChatViewModel.swift
Gates Tor and Nostr startup behind explicit conditions and hardens the lifecycle:
- Do not start Tor or connect to relays unless either (a) location permissions are authorized, or (b) at least one mutual favorite exists.
- On background, fully stop Tor for a deterministic, clean restart on foreground (when allowed).
- When conditions become disallowed, disconnect all relays and stop Tor.
- Prevent any Nostr reconnect attempts, subscriptions or sends while disabled.
- Improve UX with clear system messages: starting, restarted, and ready.
- Avoid launching network services when users have not opted-in (no location + no mutual favorites).
- Reduce power/network usage and avoid error-prone half-suspended Tor states when the app backgrounds for a while.
- Eliminate double-start and reconnect …
=> Gate Tor/Nostr start behind permissions or mutual favorites; clean lifecycle + UX

bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/ContentView.swift
- resolve display name & identity for geohash posts before showing the message action sheet
- block the sheet when the linked message belongs to the local user
- add a short-key mapping on geohash sends so subsequent lookups succeed
- xcodebuild -project bitchat.xcodeproj -scheme "bitchat (macOS)" -configuration Debug CODE_SIGNING_ALLOWED=NO build
=> Ignore self when opening message actions

bitchat/Nostr/NostrRelayManager.swift, bitchat/Services/NetworkActivationService.swift, bitchat/Services/Tor/TorManager.swift, bitchat/Services/Tor/TorNotifications.swift, bitchat/Services/Tor/TorURLSession.swift, bitchat/ViewModels/ChatViewModel.swift, bitchat/Views/LocationChannelsSheet.swift
- gate default nostr relays on mutual favorites and react to changes
- add tor toggle in location channels sheet with direct relay support
- ensure tor shutdown/reset and status messaging follow preference flips
- not run (please run Command line invocation:
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project bitchat.xcodeproj -scheme bitchat -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15" test
Build settings from command line:
SDKROOT = iphonesimulator26.0
Resolve Package Graph
Resolved source packages:
swift-secp256k1: https://github.com/21-DOT-DEV/swift-secp256k1 @ 0.21.1
BitLogger: /Users/jack/vibe/bitchat/localPackages/BitLogger @ local)
=> add option to turn off tor, gate default relays connection on mutual favorites

bitchat/Localizable.xcstrings
- add Vietnamese, Filipino/Tagalog, Malay, Polish, Dutch, Swedish, Tamil, and
Urdu strings to the localization catalog
- align Bluetooth, Tor, and system prompts with region-specific terminology
while preserving placeholders
- validate `Localizable.xcstrings` formatting to ensure the expanded catalog
stays parseable
- not run (please run `xcodebuild -project bitchat.xcodeproj -scheme bitchat
-sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
test`)
=> Add new languages

Package.swift, bitchatTests/LocationNotesManagerTests.swift
Two tests in `LocationNotesManagerTests` were failing due to a localization key mismatch:
- `testSubscribeWithoutRelaysSetsNoRelaysState`
- `testSendWhenNoRelaysSurfacesError`
**Error**: Tests expected localized string `"no geo relays available near this location. try again soon."` but received localization key `"location_notes.error.no_relays"`.
In test environments, Swift's `String(localized:)` returns the localization key instead of the translated value, causing assertion failures.
Updated test assertions to expect the localization key that's actually returned in the test environment:
```swift
// Before
XCTAssertEqual(manager.errorMessage, "no geo relays available near this location. try again soon.")
// After  
XCTAssertEqual(manager.errorMessage, "location_notes.error.no_relays")
``` …
=> Fix broke tests with LocationNotesManagerTests to expect localization key

bitchatTests/LocalizationCatalogTests.swift, bitchatTests/LocationNotesManagerTests.swift
Following #702 - I think it's better to temporarily comment them out so we can catch actual issues with CI
=> Temporarily disable broken tests to catch actual issues

bitchat/Services/BLEService.swift, bitchat/Sync/GossipSyncManager.swift
Ghost peers from yesterday appeared on app restart, then disappeared after 5 seconds. Restarting the app brought them back. Also seeing stale messages from yesterday appearing in the mesh timeline.
**Vector 1: Gossip Sync Storage**
- `GossipSyncManager` stored packets indefinitely (capacity limit only, no time limit)
- Peers running 24+ hours accumulated day-old announces in storage
- When a peer restarts with empty gossip storage, it receives ALL stored messages from other peers (up to 1000 messages)
**Vector 2: Packet Processing**
- `handleAnnounce` and `handleMessage` had no timestamp validation
- They accepted packets from ANY timestamp, even from yesterday
- Even with gossip filtering, old announces could arrive via relayed paths or from peers running old code …
=> Fix ghost peers and stale messages from gossip sync

bitchat.xcodeproj/project.pbxproj
Tor's xcframework used to be treated in the .xcodeproj file as a static library with "Do Not Embed" before #602 - and it was removed in #602. This caused testflight uploads to show a warning, but still successfully upload.
Adding it again with the same "Do Not Embed" removes the testflight warning and works as before.
| Before | After |
| - | - |
| <img width="559" height="178" alt="Screenshot 2025-10-07 at 12 44 18 AM" src="https://github.com/user-attachments/assets/261fed44-bb60-4ecf-a5a1-0311cd535417" /> | <img width="555" height="169" alt="Screenshot 2025-10-07 at 12 43 26 AM" src="https://github.com/user-attachments/assets/c2edf583-180f-4ba7-aed9-f038c74df989" /> |
=> Add Tor’s xcframework and select “Do not embed”
