.github/workflows/check.yml

This PR introduces a GitHub Actions workflow to automate checks on pull requests. It runs the test suite on an iOS simulator to ensure that changes are safe to merge.
Please note that some tests are currently failing. This is a known issue that is out of scope for this PR, but will hopefully be fixed soon.

Set up CI using GitHub Actions

---

.gitignore
bitchat.xcodeproj/project.pbxproj
bitchatTests/EndToEnd/PrivateChatE2ETests.swift
bitchatTests/EndToEnd/PublicChatE2ETests.swift
bitchatTests/Integration/IntegrationTests.swift
bitchatTests/Mocks/MockBluetoothMeshService.swift
bitchatTests/Mocks/MockNoiseSession.swift
bitchatTests/Noise/NoiseProtocolTests.swift
bitchatTests/Protocol/BinaryProtocolTests.swift
bitchatTests/TestUtilities/TestConstants.swift
bitchatTests/TestUtilities/TestHelpers.swift

- Created comprehensive test suite covering all major components of bitchat
- Tests include protocol layer, encryption, public/private messaging, and network scenarios
- All tests build successfully on both iOS and macOS platforms
- Binary protocol encoding/decoding
- Message compression and padding
- Protocol version handling
- XX pattern handshake flows
- Bidirectional encryption/decryption
- Session management and key rotation
- Security tests (tamper detection, replay prevention)
- Public message broadcasting and routing
- Private message delivery with ACKs
- Message retry logic
- TTL handling and duplicate prevention
- Multi-hop relay scenarios
- Full mesh network communication
- Dynamic topology changes
- Network partition recovery
- Mixed traffic patterns
- High load scenarios
- …

Add comprehensive test suite

---

bitchat/BitchatApp.swift
bitchat/Protocols/BitchatProtocol.swift
bitchat/Services/NotificationService.swift
bitchat/ViewModels/ChatViewModel.swift
bitchat/Views/ContentView.swift
bitchat/Views/LinkPreviewView.swift

- Comprehensive UI polish improvements for better user experience
- 8 performance optimizations to make the app extremely responsive
- Fixed various UI inconsistencies and spacing issues
- ✅ Made entire peer list row tappable (excluding favorite star)
- ✅ Fixed 1px grey bar visibility when swiping private chat
- ✅ Added action sheet for chat messages with PM/hug/slap/block options
- ✅ Fixed PM notifications to not show when chat is open, and open correct chat on tap
- ✅ Added nickname validation to prevent empty names (defaults to anon+numbers)
- ✅ Removed <name> label from chat input box
- ✅ Set message limit to 1337 before trimming old messages
- ✅ Removed RSSI-based sender name coloring in chat messages
- ✅ Bold user's own nickname in chat messages
- ✅ Added 1px more space between chat …

UI Polish and Performance Optimizations

---

bitchat/Protocols/BitchatProtocol.swift
bitchat/Services/BluetoothMeshService.swift
bitchat/ViewModels/ChatViewModel.swift
bitchat/Views/ContentView.swift

- Added comprehensive MARK headers to improve navigation in large files
- Fixed duplicate functions and consolidated related code
- Improved code organization across major service files
- Added MARK sections for all major functional areas
- Removed duplicate `getCurrentPeerID(for:)` function
- Consolidated peer management functions into cohesive sections
- Moved identity cache methods to proper location
- Added MARK headers for all sections
- Moved floating `handleHandshakeRequest()` to Message Reception section
- Consolidated message trimming functions into Message Batching section
- Added documentation for complex inline computations
- Improved readability with explanatory comments
- Added MARK headers to BitchatProtocol.swift
- NoiseProtocol.swift already had appropriate organization

Improve code organization and documentation

---

AI_CONTEXT.md
bitchat/Identity/IdentityModels.swift
bitchat/Identity/SecureIdentityStateManager.swift
bitchat/Noise/NoiseProtocol.swift
bitchat/Protocols/BinaryProtocol.swift
bitchat/Protocols/BitchatProtocol.swift
bitchat/Services/BluetoothMeshService.swift
bitchat/Services/NoiseEncryptionService.swift
bitchat/ViewModels/ChatViewModel.swift

- Added extensive documentation to help AI assistants understand the BitChat codebase
- Created AI_CONTEXT.md as a central documentation hub
- Documented all core components with detailed explanations
- **AI_CONTEXT.md**: Comprehensive project overview including architecture, core components, development guidelines, and quick start guide
- **BluetoothMeshService.swift**: Core networking, mesh protocol, connection lifecycle
- **BitchatProtocol.swift**: Protocol design, message types, security considerations  
- **NoiseProtocol.swift**: Cryptographic implementation, handshake flow, security properties
- **ChatViewModel.swift**: MVVM architecture, business logic, command system
- **IdentityModels.swift**: Three-layer identity model, privacy design
- **NoiseEncryptionService.swift**: …

Add comprehensive AI-friendly documentation

---

bitchat.xcodeproj/project.pbxproj
bitchat/Noise/NoiseProtocol.swift
bitchat/Noise/NoiseSession.swift
bitchat/Nostr/NostrIdentity.swift
bitchat/Protocols/BitchatProtocol.swift
bitchat/Services/BluetoothMeshService.swift
bitchat/Services/KeychainManager.swift
bitchat/Utils/InputValidator.swift

This PR addresses several security vulnerabilities and improves the overall security posture of the application.
- Created InputValidator utility class for comprehensive validation
- Added validation for peer IDs, nicknames, message content, and protocol fields
- Prevents injection attacks, buffer overflows, and malformed data
- Fixed force unwrapping in NostrIdentity.swift bech32 functions
- Added ASCII validation before processing to prevent crashes on invalid input
- Improved sandbox detection using multiple verification methods
- Enforced consistent app group usage for better isolation
- Enhanced panic mode deletion to only affect BitChat items
- Implemented secure memory clearing for sensitive cryptographic data
- Added clearSensitiveData() to NoiseCipherState
- Clear shared secrets …

Security fixes and improvements

---

bitchat/Services/BluetoothMeshService.swift
bitchat/ViewModels/ChatViewModel.swift
bitchat/Views/ContentView.swift

This PR implements three high-impact performance optimizations identified through codebase analysis:
- Replaced `VStack` with `LazyVStack` in the message list view
- Messages now render on-demand instead of all 1337 at once
- Significantly reduces memory usage and initial render time
- Removed redundant `DispatchQueue.main.async` wrappers around `scheduleUIUpdate()`
- Made `scheduleUIUpdate()` thread-safe with main thread detection
- Reduces unnecessary thread hopping and main thread congestion
- Consolidated 12 separate timers into 3 frequency-based timers:
- **High frequency (2s)**: Critical real-time tasks
- **Medium frequency (20s)**: Regular maintenance tasks
- **Low frequency (5min)**: Cleanup and optimization tasks
- Reduces timer overhead and improves CPU efficiency
These …

Performance optimizations: LazyVStack, UI batching, timer consolidation

---

bitchat/Services/BluetoothMeshService.swift

- Extend timeouts for better stability (availability: 30s→60s, cleanup: 3min→5min)
- Enable 30% relay probability for small networks to help discovery
- Add macOS-specific fixes for CoreBluetooth compatibility
- Implement rescan rate limiting to prevent battery drain
- Add comprehensive debug logging for network diagnostics
- Fix peripheral mapping and connection state management
- Improve relay-only session handling
Network connections were flaky with peers not consistently discovering each other:
- Mac seeing 0 peers despite others seeing Mac
- Sol and Jack unable to discover each other
- Connections dropping after 10-20 seconds
- Excessive "Marking as active despite no peripheral" messages
This PR addresses the core stability issues by:
1. Giving connections more time before cleanup
2. …

Fix network flakiness and improve peer discovery

---

bitchat/Services/BluetoothMeshService.swift

While implementing a [linux rust client for bitchat](https://github.com/spr-networks/bitchat-plugin), I found a security flaw with DMs.
The state machine on iOS will mistakenly accept plaintext messages to display. This allows an adversary to impersonate a user inside of a trusted chat. 
This code patch adds a decrypted: bool parameter to the packet handler to mark when a message actually came from inside of a trusted & decrypted noise message. 
Perhaps an alert should be presented, but for now, this will silently drop the message in the UI and log the spoofing attempt to the console.
Reproducability:
The bug can be tested with the plugin by sending a command with /plain to inject a plaintext DM.

[security] Prevent spoofable plaintext messages from sliding into private chats

---

bitchat/Services/BluetoothMeshService.swift

Resubmission of https://github.com/permissionlesstech/bitchat/pull/412
This adds a decrypted parameter to message processing to more clearly mark when a message came from e2e decryption

Prevent spoofable plaintext messages from sliding into private chats

---

bitchat/Services/SimplifiedBluetoothService.swift

use TLV encoding for messagepayloads

---

bitchat/Nostr/NostrProtocol.swift

Nostr: sign events directly with Schnorr keys; remove Signing.PrivateKey conversions
Summary
- Make Nostr event signing explicit with BIP‑340 Schnorr keys by updating the signing API and call sites.
- Remove temporary conversions from `P256K.Schnorr.PrivateKey` → `P256K.Signing.PrivateKey` → back to Schnorr during sign.
- Aligns code with NIP‑01/NIP‑17 expectations and reduces key‑type churn.
What Changed
- API: `NostrEvent.sign` now takes `P256K.Schnorr.PrivateKey` (was `P256K.Signing.PrivateKey`).
- Call sites:
- `createEphemeralGeohashEvent`: uses `senderIdentity.schnorrSigningKey()` and calls `event.sign(with:)` directly.
- `createSeal` and `createGiftWrap`: sign with the Schnorr private keys directly (no conversions).
- Removed “temporary until we update sign method” comments …

Nostr: sign events directly with Schnorr keys; remove Signing.PrivateKey conversions

---

bitchat.xcodeproj/project.pbxproj

This helps avoid manually updating the version in multiple places
https://github.com/user-attachments/assets/771655d7-0bb0-4996-8bed-c2c79fb3e000

Single source of truth for Marketing Version

---

WHITEPAPER.md

Added mermaid diagrams for BitchatPacket and BitchatMessage structures.

Include mermaid diagrams for packet structures

---

bitchatTests/Localization/LocalizationCatalogTests.swift

Add comprehensive regression tests to prevent localization format string crashes and ensure translation completeness. These tests complement the recently merged Swift String Catalogs migration ([#691](https://github.com/permissionlesstech/bitchat/pull/691)) by providing runtime safety validation.
The failed tests should be fixed once https://github.com/permissionlesstech/bitchat/pull/699 is merged to main
- Add 7 regression tests for pluralized format strings (`%#@variable@` syntax)
- Test edge cases: large numbers, zero values, empty strings
- Validate format string argument matching to prevent crashes
- Ensure `String(localized:)` calls don't throw runtime exceptions
- Maintain existing structural validation tests (locale parity, placeholder consistency)
- All tests build successfully …

Chore: Add localization regression tests to prevent format string crashes

---

bitchat/Noise/NoiseSecurityConsiderations.swift
bitchat/Services/FavoritesPersistenceService.swift
bitchat/Services/MessageRouter.swift
bitchat/Services/NoiseEncryptionService.swift
bitchat/Services/NostrTransport.swift

PeerID 8/n: NoiseRateLimiter & FavoritesPersistenceService

---

bitchat/Models/PeerID.swift
bitchat/Services/BLEService.swift
bitchat/Services/MessageRouter.swift
bitchat/Services/NoiseEncryptionService.swift
bitchat/Services/PrivateChatManager.swift
bitchat/Services/UnifiedPeerService.swift
bitchat/ViewModels/ChatViewModel.swift

PeerID 10/n: MessageRouter

---

bitchat/Protocols/BitchatProtocol.swift
bitchat/Views/Components/DeliveryStatusView.swift
bitchat/Views/ContentView.swift

Extract `DeliveryStatusView` into a separate file

---

bitchat/Models/BitchatMessage.swift
bitchat/Models/BitchatPacket.swift
bitchat/Models/BitchatPeer.swift
bitchat/Models/PeerID.swift
bitchat/Services/BLEService.swift
bitchat/Services/Transport.swift
bitchat/Services/UnifiedPeerService.swift
bitchat/Utils/PeerDisplayNameResolver.swift
bitchat/ViewModels/ChatViewModel.swift
bitchat/Views/ContentView.swift
bitchat/Views/LocationChannelsSheet.swift
bitchat/Views/MeshPeerList.swift
bitchatTests/EndToEnd/PublicChatE2ETests.swift
bitchatTests/Integration/IntegrationTests.swift
bitchatTests/Mocks/MockBLEService.swift
bitchatTests/Protocol/BinaryProtocolTests.swift
bitchatTests/TestUtilities/TestHelpers.swift

PeerID 16/n: BitchatPeer / PeerInfo / TransportPeer

---

bitchat/Protocols/Geohash.swift
bitchat/Services/LocationNotesCounter.swift
bitchat/Services/LocationNotesManager.swift
bitchat/Views/ContentView.swift
bitchat/Views/LocationNotesView.swift
bitchatTests/LocationNotesManagerTests.swift

Comprehensive robustness fixes for location notes feature based on deep architectural analysis. All critical and moderate priority issues addressed.
**#1: O(1) Duplicate Detection**
- **Before:** O(n) linear search through notes array on every incoming event
- **After:** O(1) Set-based lookup with `noteIDs`
- **Impact:** Eliminates UI lag when receiving 200+ notes during initial EOSE
- Added `private var noteIDs = Set<String>()` for fast duplicate checking
**#2: Optimistic Echo Timestamp**
- **Before:** Used `dependencies.now()` creating milliseconds-off timestamp
- **After:** Uses `Date(timeIntervalSince1970: TimeInterval(event.created_at))`
- **Impact:** Optimistic echo now has exact same timestamp as signed event
- Prevents sort order issues and ensures relay echo deduplication works …

Location notes: fix performance and UI issues
